name: dislife
description: "Transform your Discord Rich Presence into a Locket-like experience: instantly share your moments with friends and peers!"
publish_to: "none"

version: 1.2.1+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.13.1
  http: ^1.2.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0
  flutter_svg: ^2.0.10+1
  lehttp_overrides: ^1.0.3
  flutter_native_splash: ^2.4.0
  flutter_markdown: ^0.7.1
  camera: ^0.11.0+1
  universal_io: ^2.2.2

flutter_native_splash:
  android: true
  ios: true
  web: true
  image: "assets/images/icons/splash_logo.png"
  color: "#F6F6F6"

  android_12:
    color: "#F6F6F6"
    image: "assets/images/icons/splash_logo_12.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/icons/curved.png
    - assets/images/icons/square.png
    - assets/images/icons/flower.svg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/curved.png"
